version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: bundle_install
          command: gem install bundler; bundle install
      - run:
          name: run_test
          command: bundle exec rspec
